// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.6.1
// source: pkg/fukabunsan/messages.proto

package fukabunsan

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_Unknown Status = 0
	Status_Success Status = 1
	Status_Failed  Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "Unknown",
		1: "Success",
		2: "Failed",
	}
	Status_value = map[string]int32{
		"Unknown": 0,
		"Success": 1,
		"Failed":  2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_fukabunsan_messages_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_pkg_fukabunsan_messages_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_pkg_fukabunsan_messages_proto_rawDescGZIP(), []int{0}
}

// Activator-LB -> Katyusha-FukaBunsan: LB
type LBRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	ID            uint32                    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Targets       []string                  `protobuf:"bytes,2,rep,name=targets,proto3" json:"targets,omitempty"`
	SourceIP      string                    `protobuf:"bytes,3,opt,name=SourceIP,proto3" json:"SourceIP,omitempty"`
	Domain        string                    `protobuf:"bytes,4,opt,name=Domain,proto3" json:"Domain,omitempty"`
	URI           string                    `protobuf:"bytes,5,opt,name=URI,proto3" json:"URI,omitempty"`
	Method        string                    `protobuf:"bytes,6,opt,name=Method,proto3" json:"Method,omitempty"`
	RequestID     string                    `protobuf:"bytes,8,opt,name=RequestID,proto3" json:"RequestID,omitempty"` // 🔥 THÊM DÒNG NÀY
	Headers       []*LBRequest_HeaderSchema `protobuf:"bytes,7,rep,name=Headers,proto3" json:"Headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LBRequest) Reset() {
	*x = LBRequest{}
	mi := &file_pkg_fukabunsan_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LBRequest) ProtoMessage() {}

func (x *LBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_fukabunsan_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LBRequest.ProtoReflect.Descriptor instead.
func (*LBRequest) Descriptor() ([]byte, []int) {
	return file_pkg_fukabunsan_messages_proto_rawDescGZIP(), []int{0}
}

func (x *LBRequest) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *LBRequest) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *LBRequest) GetSourceIP() string {
	if x != nil {
		return x.SourceIP
	}
	return ""
}

func (x *LBRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *LBRequest) GetURI() string {
	if x != nil {
		return x.URI
	}
	return ""
}

func (x *LBRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *LBRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *LBRequest) GetHeaders() []*LBRequest_HeaderSchema {
	if x != nil {
		return x.Headers
	}
	return nil
}

type LBResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Target        string                     `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Headers       []*LBResponse_HeaderSchema `protobuf:"bytes,2,rep,name=Headers,proto3" json:"Headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LBResponse) Reset() {
	*x = LBResponse{}
	mi := &file_pkg_fukabunsan_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LBResponse) ProtoMessage() {}

func (x *LBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_fukabunsan_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LBResponse.ProtoReflect.Descriptor instead.
func (*LBResponse) Descriptor() ([]byte, []int) {
	return file_pkg_fukabunsan_messages_proto_rawDescGZIP(), []int{1}
}

func (x *LBResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *LBResponse) GetHeaders() []*LBResponse_HeaderSchema {
	if x != nil {
		return x.Headers
	}
	return nil
}

type LBRequest_HeaderSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LBRequest_HeaderSchema) Reset() {
	*x = LBRequest_HeaderSchema{}
	mi := &file_pkg_fukabunsan_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LBRequest_HeaderSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LBRequest_HeaderSchema) ProtoMessage() {}

func (x *LBRequest_HeaderSchema) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_fukabunsan_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LBRequest_HeaderSchema.ProtoReflect.Descriptor instead.
func (*LBRequest_HeaderSchema) Descriptor() ([]byte, []int) {
	return file_pkg_fukabunsan_messages_proto_rawDescGZIP(), []int{0, 0}
}

func (x *LBRequest_HeaderSchema) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *LBRequest_HeaderSchema) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LBResponse_HeaderSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LBResponse_HeaderSchema) Reset() {
	*x = LBResponse_HeaderSchema{}
	mi := &file_pkg_fukabunsan_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LBResponse_HeaderSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LBResponse_HeaderSchema) ProtoMessage() {}

func (x *LBResponse_HeaderSchema) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_fukabunsan_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LBResponse_HeaderSchema.ProtoReflect.Descriptor instead.
func (*LBResponse_HeaderSchema) Descriptor() ([]byte, []int) {
	return file_pkg_fukabunsan_messages_proto_rawDescGZIP(), []int{1, 0}
}

func (x *LBResponse_HeaderSchema) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *LBResponse_HeaderSchema) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_pkg_fukabunsan_messages_proto protoreflect.FileDescriptor

const file_pkg_fukabunsan_messages_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/fukabunsan/messages.proto\x12\n" +
	"fukabunsan\"\xab\x02\n" +
	"\tLBRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\rR\x02ID\x12\x18\n" +
	"\atargets\x18\x02 \x03(\tR\atargets\x12\x1a\n" +
	"\bSourceIP\x18\x03 \x01(\tR\bSourceIP\x12\x16\n" +
	"\x06Domain\x18\x04 \x01(\tR\x06Domain\x12\x10\n" +
	"\x03URI\x18\x05 \x01(\tR\x03URI\x12\x16\n" +
	"\x06Method\x18\x06 \x01(\tR\x06Method\x12\x1c\n" +
	"\tRequestID\x18\b \x01(\tR\tRequestID\x12<\n" +
	"\aHeaders\x18\a \x03(\v2\".fukabunsan.LBRequest.HeaderSchemaR\aHeaders\x1a:\n" +
	"\fHeaderSchema\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x9f\x01\n" +
	"\n" +
	"LBResponse\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12=\n" +
	"\aHeaders\x18\x02 \x03(\v2#.fukabunsan.LBResponse.HeaderSchemaR\aHeaders\x1a:\n" +
	"\fHeaderSchema\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value*.\n" +
	"\x06Status\x12\v\n" +
	"\aUnknown\x10\x00\x12\v\n" +
	"\aSuccess\x10\x01\x12\n" +
	"\n" +
	"\x06Failed\x10\x02B\x10Z\x0epkg/fukabunsanb\x06proto3"

var (
	file_pkg_fukabunsan_messages_proto_rawDescOnce sync.Once
	file_pkg_fukabunsan_messages_proto_rawDescData []byte
)

func file_pkg_fukabunsan_messages_proto_rawDescGZIP() []byte {
	file_pkg_fukabunsan_messages_proto_rawDescOnce.Do(func() {
		file_pkg_fukabunsan_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_fukabunsan_messages_proto_rawDesc), len(file_pkg_fukabunsan_messages_proto_rawDesc)))
	})
	return file_pkg_fukabunsan_messages_proto_rawDescData
}

var file_pkg_fukabunsan_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_fukabunsan_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_fukabunsan_messages_proto_goTypes = []any{
	(Status)(0),                     // 0: fukabunsan.Status
	(*LBRequest)(nil),               // 1: fukabunsan.LBRequest
	(*LBResponse)(nil),              // 2: fukabunsan.LBResponse
	(*LBRequest_HeaderSchema)(nil),  // 3: fukabunsan.LBRequest.HeaderSchema
	(*LBResponse_HeaderSchema)(nil), // 4: fukabunsan.LBResponse.HeaderSchema
}
var file_pkg_fukabunsan_messages_proto_depIdxs = []int32{
	3, // 0: fukabunsan.LBRequest.Headers:type_name -> fukabunsan.LBRequest.HeaderSchema
	4, // 1: fukabunsan.LBResponse.Headers:type_name -> fukabunsan.LBResponse.HeaderSchema
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_fukabunsan_messages_proto_init() }
func file_pkg_fukabunsan_messages_proto_init() {
	if File_pkg_fukabunsan_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_fukabunsan_messages_proto_rawDesc), len(file_pkg_fukabunsan_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_fukabunsan_messages_proto_goTypes,
		DependencyIndexes: file_pkg_fukabunsan_messages_proto_depIdxs,
		EnumInfos:         file_pkg_fukabunsan_messages_proto_enumTypes,
		MessageInfos:      file_pkg_fukabunsan_messages_proto_msgTypes,
	}.Build()
	File_pkg_fukabunsan_messages_proto = out.File
	file_pkg_fukabunsan_messages_proto_goTypes = nil
	file_pkg_fukabunsan_messages_proto_depIdxs = nil
}
